### ISSUE TITLE
deme有点问题，不需要订阅消息

### ISSUE THREAD

**Issue by liangdas** [lulucas/mqant-UnityExample#1]
聊天室DEMO没有用mqtt协议的订阅行为

Chat/HD_JoinChat/{msgid} 其实也是给服务器publish了一条消息过去，这时服务器会记录下这个用户的session，当其他用户通过Chat/HD_Say/{msg_id}发送聊天消息的时候服务器就会给这些session转播聊天消息

服务器给客户端广播的消息协议是

当有用户加入聊天室: Chat/OnJoin
当有用户聊天：Chat/OnChat

详细可见:
https://github.com/liangdas/mqant/wiki/mqant%E7%9A%84HelloWorld
https://github.com/liangdas/mqantserver/blob/master/src/client/mqtt_chat_client.py

**Comment by lulucas** [comment]
已移除多余的订阅代码
